#!/bin/bash
# Step 4b: Lightweight finetune to restore fluency on the suppressed adapter.
# Continues training from outputs/purified/suppressed_adapter on data/finetune_clean.json
# using the config generated by step2 at outputs/training/configs/finetune_after_suppression.yaml.
# Output: outputs/purified/finetuned/ (the FINAL purified adapter for paper numbers).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$PROJECT_DIR/base_select_gpu.sh"

cd "$PROJECT_DIR"
source "$PROJECT_DIR/scripts/_load_cfg.sh"

FT_CONFIG="${TRAINING_DIR}/configs/finetune_after_suppression.yaml"
SUPPRESSED_ADAPTER="${PURIFIED_DIR}/suppressed_adapter"
OUTPUT_DIR="${PURIFIED_DIR}/finetuned"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/step4b_finetune.log"

# Verify prerequisites: step4 (suppressed adapter) + the generated finetune config.
if [ ! -f "$SUPPRESSED_ADAPTER/adapter_model.safetensors" ]; then
    echo "ERROR: suppressed adapter not found at $SUPPRESSED_ADAPTER" >&2
    echo "       Run scripts/step4_purify.sh first." >&2
    exit 1
fi
if [ ! -f "$FT_CONFIG" ]; then
    echo "ERROR: finetune config not found at $FT_CONFIG" >&2
    echo "       Run step2_generate_training.py (or scripts/step2_train_variants.sh prereq) first." >&2
    exit 1
fi

# Sanity check: the yaml MUST point at the suppressed adapter, not the suspicious one.
if ! grep -qF "$SUPPRESSED_ADAPTER" "$FT_CONFIG"; then
    echo "ERROR: $FT_CONFIG does not reference the suppressed adapter ($SUPPRESSED_ADAPTER)." >&2
    echo "       Re-generate with step2_generate_training.py — the fixed version writes the correct path." >&2
    exit 1
fi

MASTER_PORT=$(( (RANDOM % 45000) + 20000 ))

echo "[step4b] GPU         : $CUDA_VISIBLE_DEVICES"
echo "[step4b] MASTER_PORT : $MASTER_PORT"
echo "[step4b] Config      : $FT_CONFIG"
echo "[step4b] From adapter: $SUPPRESSED_ADAPTER"
echo "[step4b] Output      : $OUTPUT_DIR"
echo "[step4b] Log         : $LOG_FILE"

python -m torch.distributed.run \
    --nproc_per_node=1 \
    --master_port="$MASTER_PORT" \
    finetune_train.py "$FT_CONFIG" \
    2>&1 | tee "$LOG_FILE"

echo "[step4b] Done. Finetuned adapter saved to: $OUTPUT_DIR"
