#!/bin/bash
# Step 4c: SAART-P1 (Self-Adversarial Consistency Immunization) — a training-time defense.
# Continues training from the SUSPICIOUS adapter (θ_sus, same as B2 pure-finetune) on
# data/finetune_clean.json, but with the self-adversarial trainer enabled (use_saart: true),
# using the config generated by step2 at outputs/training/configs/saart_p1_immunize.yaml.
# Output: outputs/purified/saart_p1/immunized/  (evaluated by step5 as tag=after_saart_p1).
#
# This runs IN PARALLEL to the BD-VAX post-hoc pipeline; it does not touch steps 3/4/4b.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$PROJECT_DIR/base_select_gpu.sh"

cd "$PROJECT_DIR"
source "$PROJECT_DIR/scripts/_load_cfg.sh"

SAART_CONFIG="${TRAINING_DIR}/configs/saart_p1_immunize.yaml"
OUTPUT_DIR="${PURIFIED_DIR}/saart_p1/immunized"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/step4c_saart.log"

# Idempotent: skip if the immunized adapter already exists.
if [ -f "$OUTPUT_DIR/adapter_model.safetensors" ]; then
    echo "[step4c] SAART-P1 adapter already exists at $OUTPUT_DIR — skipping."
    exit 0
fi

# Prerequisites: θ_sus + the generated SAART config (run step2_generate_training.py first).
if [ ! -f "$SUSPICIOUS_ADAPTER/adapter_model.safetensors" ]; then
    echo "ERROR: suspicious adapter not found at $SUSPICIOUS_ADAPTER" >&2
    echo "       Train it (scripts/step0_badnet_negsenti.sh) first." >&2
    exit 1
fi
if [ ! -f "$SAART_CONFIG" ]; then
    echo "ERROR: SAART config not found at $SAART_CONFIG" >&2
    echo "       Run: python step2_generate_training.py --config \"\$CFG_FILE\"" >&2
    echo "       (the experiment.yaml must contain a 'saart:' block)." >&2
    exit 1
fi

# Hard checks: the config MUST enable SAART and continue from an adapter.
if ! grep -q "^use_saart: true" "$SAART_CONFIG"; then
    echo "ERROR: $SAART_CONFIG does not set 'use_saart: true'." >&2
    exit 1
fi
if ! grep -q "^adapter_name_or_path:" "$SAART_CONFIG"; then
    echo "ERROR: $SAART_CONFIG has no adapter_name_or_path (SAART must continue from θ_sus)." >&2
    exit 1
fi
# Soft check (warning only): absolute/relative path forms may legitimately differ.
if ! grep -qF "$SUSPICIOUS_ADAPTER" "$SAART_CONFIG"; then
    echo "[step4c] WARNING: $SAART_CONFIG does not literally reference \$SUSPICIOUS_ADAPTER." >&2
    echo "         Make sure the adapter_name_or_path points at θ_sus." >&2
fi

MASTER_PORT=$(( (RANDOM % 45000) + 20000 ))

echo "[step4c] GPU         : $CUDA_VISIBLE_DEVICES"
echo "[step4c] MASTER_PORT : $MASTER_PORT"
echo "[step4c] Config      : $SAART_CONFIG"
echo "[step4c] From adapter: $SUSPICIOUS_ADAPTER (θ_sus)"
echo "[step4c] Output      : $OUTPUT_DIR"
echo "[step4c] Log         : $LOG_FILE"

python -m torch.distributed.run \
    --nproc_per_node=1 \
    --master_port="$MASTER_PORT" \
    saart_train.py "$SAART_CONFIG" \
    2>&1 | tee "$LOG_FILE"

echo "[step4c] Done. SAART-P1 immunized adapter saved to: $OUTPUT_DIR"
